id: P000723
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG22943
  title: ཐུའུ་བཀྭན་གྲུབ་མཐའ།
  author: ''
  volumes:
    a352d17ae96942528901888e2a5cf451:
      image_group_id: I1KG22982
      title: ''
      volume_number: 1
      total_pages: 550
      base_file: v001.txt
